### ISSUE TITLE
Simple sync server and client

### ISSUE THREAD

**Issue by delebash** [nponiros/sync_client#6]
Your code is to complex for me and I was hoping you might have a very basic client server websocket example.  The [websockect example](https://github.com/dfahlander/Dexie.js/tree/master/samples/remote-sync/websocket)  looks like what I am looking for but I can't get it working. I am trying to have a simple page with two buttons connect and add so I can see in a simple way how these components work.

I am sure you are busy, but if you get a chance anything will help.  Also I noticed that v2.0 has improved the syncable component thanks to you so kudos.

**Comment by nponiros** [comment]
Unfortunatelly I don't have a client websocket example just https://github.com/nponiros/sync_server which has websocket support but I'm guessing that is the code you found complex.

What is the issue with the example in the dexie repo? Maybe you can post the error or show me your code.

**Comment by delebash** [comment]
[This issue](https://github.com/dfahlander/Dexie.js/issues/433) fixed my original problem of db.hasBeenClosed  but now it stays at Sync Status changed: CONNECTING.  No data is added.
[TestServerClients.zip](https://github.com/nponiros/sync_client/files/1253957/TestServerClients.zip)

**Comment by nponiros** [comment]
Okay, I will try to have a look tomorrow. It's pretty late here

**Comment by delebash** [comment]
Thank you and have a good night.

**Comment by nponiros** [comment]
So I spent over an hour trying to get this thing to work with no success. As it seems data is sent to the server but the server is not receiving the data. It might be some incompatibility issue between the server/client websocket implementation it might also be some other error because the client also didn't write any data into indexeddb. I'm afraid I can't help you with this.. Perhaps someone can help if you open an issue on the dexie repo..

**Comment by delebash** [comment]
Thank you very much for trying and putting so much time in. I really appreciate it!
